#ifndef __ETL_PROFILE_H__
#define __ETL_PROFILE_H__

#define ETL_VERBOSE_ERRORS
#define ETL_CHECK_PUSH_POP

// #define ETL_COMPILER_GCC
// #define ETL_TARGET_DEVICE_ARM
// #define ETL_TARGET_OS_NONE
// #define ETL_COMPILER_ARM6
// #define ETL_COMPILER_GCC
#define ETL_CPP11_SUPPORTED 0
#define ETL_CPP14_SUPPORTED 0
#define ETL_CPP17_SUPPORTED 0
// #define ETL_NO_NULLPTR_SUPPORT (__cplusplus < 201103L)
// #define ETL_NO_LARGE_CHAR_SUPPORT  (__cplusplus < 201103L)
// #define ETL_CPP11_TYPE_TRAITS_IS_TRIVIAL_SUPPORTED 0
// #define ETL_NO_STL

#endif
